name: CI

on:
  push:
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: javaJDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: build
        run: gradle shadow

      - name: upload
        uses: actions/upload-artifact@v1.0.0
        with:
          name: FloatingChat
          path: build/libs/*.jar
